// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLIJ4xeOVNqlRCfrEVlJKP_0idwX4j1FM',
    appId: '1:865966306402:web:6f1677e44a66af2b1bcd3b',
    messagingSenderId: '865966306402',
    projectId: 'pal48checkpoint',
    authDomain: 'pal48checkpoint.firebaseapp.com',
    storageBucket: 'pal48checkpoint.firebasestorage.app',
    measurementId: 'G-VQLHJMMCKY',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrcIsDmd1SldyGhH7EDYNwO0ptBxTRFtE',
    appId: '1:865966306402:ios:c624f5adaf43cbb41bcd3b',
    messagingSenderId: '865966306402',
    projectId: 'pal48checkpoint',
    storageBucket: 'pal48checkpoint.firebasestorage.app',
    iosBundleId: 'com.example.checkpointApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrcIsDmd1SldyGhH7EDYNwO0ptBxTRFtE',
    appId: '1:865966306402:ios:c624f5adaf43cbb41bcd3b',
    messagingSenderId: '865966306402',
    projectId: 'pal48checkpoint',
    storageBucket: 'pal48checkpoint.firebasestorage.app',
    iosBundleId: 'com.example.checkpointApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLIJ4xeOVNqlRCfrEVlJKP_0idwX4j1FM',
    appId: '1:865966306402:web:2dac5685e19a87011bcd3b',
    messagingSenderId: '865966306402',
    projectId: 'pal48checkpoint',
    authDomain: 'pal48checkpoint.firebaseapp.com',
    storageBucket: 'pal48checkpoint.firebasestorage.app',
    measurementId: 'G-J9K1G81D9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD11OyNpBiUSva9qD-7ugdc71ZIr7UiIeE',
    appId: '1:865966306402:android:3e482e66eb21e0331bcd3b',
    messagingSenderId: '865966306402',
    projectId: 'pal48checkpoint',
    storageBucket: 'pal48checkpoint.firebasestorage.app',
  );

}